### ISSUE TITLE
Build broken in emacs-head@30

### ISSUE THREAD

**Issue by jmckitrick** [daviderestivo/homebrew-emacs-head#193] opened 2023-12-28 11:28 UTC
I've tried building for a couple of days now, and I'm consistently getting this error:

```
nsterm.m:6173:3: error: call to undeclared function 'safe_call2'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  safe_call2 (Qrun_hook_with_args,
  ^
```

**Comment by jmckitrick** [comment] 2023-12-29 10:23
I figured out the issue, and I'm working on a patch.

**Comment by jmckitrick** [comment] 2024-01-01 13:39
It seems they fixed it upstream.

**Comment by malcolmpurvis** [comment] 2024-01-02 01:28
I can successfully build the last upstream version of Emacs 30, but the problem remains here as of when I type this.  The problem is the call to `safe_call2` in the patch `0005-System-appearance.patch` but `safe_call2` seems to have been removed from emacs.

**Comment by jmckitrick** [comment] 2024-01-02 11:56
I closed this issue prematurely. I have a PR open that fixes it when I build and install locally. Hopefully it can be reviewed and merged soon.

**Comment by jmckitrick** [comment] 2024-01-02 14:25
@malcolmpurvis Please try this:

1. Check out my PR locally
2. Run this command:

`HOMEBREW_USE_LOCAL_RESOURCES=1 brew install Formula/emacs-head@30.rb --with-cocoa`

Feel free to add other options as needed. Please let me know if it works for you.

**Comment by daviderestivo** [comment] 2024-01-03 08:18
Ciao guys, I was on holiday ... lemme have a look into this.

**Comment by daviderestivo** [comment] 2024-01-03 08:23
@jmckitrick: I have merged your https://github.com/daviderestivo/homebrew-emacs-head/pull/194. Thanks a lot for your help :).

**Closed** 2024-01-03 08:24 UTC

**Comment by malcolmpurvis** [comment] 2024-01-04 00:24
I can confirm that I can build Emacs again.   Thanks.
