### ISSUE TITLE
Display changes to frame settings

### ISSUE THREAD

**Issue by jmckitrick** [daviderestivo/homebrew-emacs-head#92] opened 2021-02-16 18:53 UTC
The latest build of HEAD on version 28 has an odd issue. Now, when I drag the emacs window from my Mac Retina display to my external display, the font is shrunk way down, and only 1/4 of the frame is filled with text.
![Screen Shot 2021-02-16 at 1 52 46 PM](https://user-images.githubusercontent.com/518057/108108170-43b36880-705e-11eb-9e1f-bb9542271ad9.png)

**Comment by jmckitrick** [comment] 2021-02-16 18:53
Not sure if this is emacs or Mac related...

**Comment by jmckitrick** [comment] 2021-02-16 21:07
https://github.com/emacs-mirror/emacs/commit/0e2b123a4ef600f5b337972a7bb61c1fc4b7d0cd

**Comment by eugene-sea** [comment] 2021-02-17 07:06
I do not have such issue, installed Emacs 28 with native-comp on 12th of Feb.

**Comment by DivineDominion** [comment] 2021-02-17 07:26
Same here, launching the .app bundle @28 freshly compiled. Don't need to drag away from the Retina MBP screen to make this happen -- it starts on my external monitor with the issue from the get go.

**Comment by eugene-sea** [comment] 2021-02-17 07:42
However, initially, I had some display issues when moving from one display to another, e.g. there was text misalignment in which-key UI, but the problem disappeared after Emacs restart.

**Comment by daviderestivo** [comment] 2021-02-17 08:56
@jmckitrick I tried but I cannot reproduce it. I'm on macOS Catalina

**Comment by DivineDominion** [comment] 2021-02-17 09:16
The commit @jmckitrick linked to originated in this patch: https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-02/msg00656.html

With emacs-head@28 the output of `(display-monitor-attributes-list)` is:

`(((geometry 0 0 3440 1440) (workarea 0 23 3440 1417) (mm-size 801 335) (frames #<frame *GNU Emacs* 0x7f970518d360>) (source . "NS")) ((geometry -1280 640 1280 800) (workarea -1280 640 1280 777) (mm-size 286 179) (frames #<frame  *Minibuf-1* 0x7f9706856c30>) (source . "NS")))`

2 frames of emacs on 2 displays look like that:

![Screen Shot 2021-02-17 at 10 11 08](https://user-images.githubusercontent.com/59080/108181952-ce50a200-7108-11eb-85d7-d6b1531fb7a5.png)
<img width="649" alt="Screen Shot 2021-02-17 at 10 11 08 (2)" src="https://user-images.githubusercontent.com/59080/108181962-d1e42900-7108-11eb-9fe1-97cb38dec79f.png">

----

I built emacs with these flags btw: 

`brew reinstall emacs-head@28 --with-cocoa --with-imagemagick --with-no-frame-refocus --with-pdumper --with-xwidgets --with-dbus --with-mailutils --with-modern-icon-sexy-v1`

**Comment by daviderestivo** [comment] 2021-02-17 10:42
> The commit @jmckitrick linked to originated in this patch: https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-02/msg00656.html

I can add this patch to Emacs-head@28 if needed. Most probably you need to wait couple of days because this week I'm really underwater ...

**Comment by jmckitrick** [comment] 2021-02-17 11:01
I’m happy to give it a shot today. What exactly needs done? It’s a Ruby-based system, so do we need to reverse the commit that caused the issue?

**Comment by DivineDominion** [comment] 2021-02-17 16:02
@daviderestivo emacs-head@28 seems to pull the patch in already, since the new `display-monitor-attributes-list` mentioned in the mailing list thread is available since then. (Just a heuristic from my part.) -- Reverting it is the best option I can come up with, but Andrii from the emacs bug thread already replied that he'd be taking a look at this. The fix might hit upstream eventually.

**Comment by daviderestivo** [comment] 2021-02-18 07:01
@DivineDominion Thanks for the clarification. If you agree, we can wait for a while to see if this is fixed upstream. In case, I can bring the patch mentioned in [here](https://lists.gnu.org/archive/html/bug-gnu-emacs/2021-02/msg00656.html) into emacs-head@28. Shall we agree on a deadline of 1 week?

**Comment by DivineDominion** [comment] 2021-02-18 07:42
A week sounds fine. I thought that the link you provided actually introduces the bug instead of fixing it, though. I guess I'll have to build emacs from source without your homebrew formula to make sure ;)

**Comment by jmckitrick** [comment] 2021-02-18 11:44
@daviderestivo Yes, it appears that patch introduces the bug. It seems the author is aware and is looking into it.

**Comment by jmckitrick** [comment] 2021-02-18 15:08
I'm happy to help the author test this patch. What's the easiest way to use this home-brew formula to build from a local emacs mirror repo with changes to test?

**Comment by daviderestivo** [comment] 2021-02-18 21:29
> A week sounds fine. I thought that the link you provided actually introduces the bug instead of fixing it, though.

Yes you're right. I was not clear enough. What I meant is that I can just make a new patch that reverts the patch of the bug#46406. I hope is more clear

**Comment by daviderestivo** [comment] 2021-02-18 21:36
> I'm happy to help the author test this patch. What's the easiest way to use this home-brew formula to build from a local emacs mirror repo with changes to test?

If the fix goes directly into emacs-mirror you can just use this formula without additional changes. Otherwise, if the author offers you a patch, the simplest is to clone emacs-mirror apply the patch on top and test it. If the fix works then we include it into emacs-head.

**Comment by jmckitrick** [comment] 2021-02-18 21:40
Well, that's the part I'm not clear on. How can I run the homebrew formula
locally and have it use my local emacs repo rather than pulling the mirror?


--
Jonathon McKitrick

**Comment by muffinmad** [comment] 2021-02-19 10:10
With the commit [0e2b123a4ef600f5b337972a7bb61c1fc4b7d0cd](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=0e2b123a4ef600f5b337972a7bb61c1fc4b7d0cd) I have no issue moving frame to the non-retina screen.  The issue appears for me with the commit [68bd6f3ea9c05637501139c46f1f4304482db95f](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=68bd6f3ea9c05637501139c46f1f4304482db95f).

I suspect this issue were introduced in [Bug#46155](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=46155).

**Comment by muffinmad** [comment] 2021-02-19 10:15
> With the commit [0e2b123a4ef600f5b337972a7bb61c1fc4b7d0cd](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=0e2b123a4ef600f5b337972a7bb61c1fc4b7d0cd) I have no issue moving frame to the non-retina screen. The issue appears for me with the commit [68bd6f3ea9c05637501139c46f1f4304482db95f](http://git.savannah.gnu.org/cgit/emacs.git/commit/?id=68bd6f3ea9c05637501139c46f1f4304482db95f).
> 
> I suspect this issue were introduced in [Bug#46155](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=46155).

@alanthird Can you please take a look at this?

**Comment by alanthird** [comment] 2021-02-19 21:54
Should be fixed on Emacs master now.

**Comment by daviderestivo** [comment] 2021-02-20 12:22
@jmckitrick @DivineDominion: could you confirm it's working as well for you and if all is fine close this issue?

**Comment by jmckitrick** [comment] 2021-02-22 12:56
All good here!

**Comment by DivineDominion** [comment] 2021-02-22 21:00
@daviderestivo Can confirm it works! (Sorry it took till Monday to get to the dual monitors to check)

**Comment by daviderestivo** [comment] 2021-02-22 21:07
@DivineDominion @jmckitrick thanks both. I'm gonna close this issue.

**Closed** 2021-02-22 21:08 UTC
Labels: emacs upstream bug
