### ISSUE TITLE
Macos M1: Emacs 28 build error: gnus-agent 

### ISSUE THREAD

**Issue by Arsca** [daviderestivo/homebrew-emacs-head#89] opened 2021-01-09 17:01 UTC
Make breaks with the following error:

> ==> ./autogen.sh
==> ./configure --enable-locallisppath=/usr/local/share/emacs/site-lisp --infodir=/usr/local/Cellar/emacs-head@28/28.0.50_1/share/info/emacs --prefix
==> make
Last 15 lines from /Users/arsca/Library/Logs/Homebrew/emacs-head@28/03.make:
In toplevel form:
gnus/gnus-agent.el:3511:1: Error: Wrong type argument: listp, file
make[2]: *** [gnus/gnus-agent.elc] Error 1
make[2]: *** Waiting for unfinished jobs....
Eager macro-expansion failure: (wrong-type-argument listp file)
Eager macro-expansion failure: (wrong-type-argument listp file)
Eager macro-expansion failure: (wrong-type-argument listp file)
Eager macro-expansion failure: (wrong-type-argument listp file)
Eager macro-expansion failure: (wrong-type-argument listp file)
Eager macro-expansion failure: (wrong-type-argument listp file)
Eager macro-expansion failure: (wrong-type-argument listp file)
Eager macro-expansion failure: (wrong-type-argument listp file)
Eager macro-expansion failure: (wrong-type-argument listp file)
make[1]: *** [compile-main] Error 2
make: *** [lisp] Error 2

**Comment by daviderestivo** [comment] 2021-01-14 06:57
Hi @Arsca, sorry for the late answer but I missed this bug report. The problem is a commit in the upstream emacs repo. It should be fixed by now.

**Closed by daviderestivo** 2021-01-14 06:57 UTC
Labels: emacs upstream bug
